
- hosts: webservers

  vars:
    nginx_port: 8080
    root_dir: /usr/share/nginx/html

  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: latest
      become: yes

    - name: copy index.html file 
      copy:
        src: ../files/index.html 
        dest: "{{root_dir}}/index.html"
      become: yes

    - name: update nginx config
      copy:
        src: ../files/nginx.conf
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx
      become: yes

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: reloaded
      become: yes

