- hosts: webservers

  tasks:
    - name: install redis server
      # bash equivalent:
      # apt-get update && apt-get install redis-server
      ansible.builtin.apt: # Ansible module name
        name: redis-server
        state: present
        update_cache: yes
      become: yes


    - name: remove redis server
      # bash equivalent:
      # apt-get remove redis-server
      ansible.builtin.apt:
        name: redis-server
        state: absent
      become: yes


