- hosts: webservers

  tasks:
    - name: install git with cache review
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: yes
      become: yes
      tags: cache_review

    - name: install git without cache review
      ansible.builtin.apt:
        name: git
        state: present
      become: yes
      tags: no_cache_review
